---
development:
  cloud_name: dxxziszp2
  api_key: '376585488377742'
  api_secret: 1AOaFhU8YWwmbwqXfDzyqwHKYKI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dxxziszp2
  api_key: '376585488377742'
  api_secret: 1AOaFhU8YWwmbwqXfDzyqwHKYKI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dxxziszp2
  api_key: '376585488377742'
  api_secret: 1AOaFhU8YWwmbwqXfDzyqwHKYKI
  enhance_image_tag: true
  static_image_support: false
